name: ProtocolSupport
main: protocolsupport.ProtocolSupport
version: 4.28-dev
author: _Shevchik_
load: STARTUP
commands:
  protocolsupport:
    description: All ProtocolSupport commands
    aliases: ps
    usage: '/protocolsupport help'